### ISSUE TITLE
Sync times out

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#116]
Reported by @nzola:

```
pi@raspberrypi:~/lokole/state $ less webapp_stderr.log
[2019-01-07 06:01:32 +0000] [808] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 06:04:57 +0000] [807] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 06:16:32 +0000] [808] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 06:31:32 +0000] [809] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 06:46:33 +0000] [807] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 07:01:32 +0000] [809] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 07:16:32 +0000] [807] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 07:31:33 +0000] [807] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 07:46:32 +0000] [808] [ERROR] Exception: Modem taking to long to connect, exiting...
[2019-01-07 08:01:32 +0000] [808] [ERROR] Exception: Modem taking to long to connect, exiting...
```

From @adamsclafani:

> Sync now has a timeout feature. If the modem takes to long to connect, it will automatically exit. The fix should just be to increase the retry count.

**Comment by nzola** [comment]
I will give it a try tonight, around 11 pm

**Comment by nzola** [comment]
Still does not work. Same error:


pi@raspberrypi:~ $ sudo wvdial
--> WvDial: Internet dialer version 1.61
--> Initializing modem.
--> Sending: ATZ
ATZ
OK
--> Sending: ATQ0
ATQ0
OK
--> Sending: AT+CGDCONT=1,"IP","apn.konekt.io"
AT+CGDCONT=1,"IP","apn.konekt.io"
OK
--> Modem initialized.
--> Sending: ATDT*99***1#
--> Waiting for carrier.
ATDT*99***1#
CONNECT
--> Carrier detected.  Starting PPP immediately.
--> Starting pppd at Sat Jan 19 08:36:21 2019
--> Pid of pppd: 1694
--> Using interface ppp0
--> pppd: ▒7▒[01]▒6▒[01]
--> pppd: ▒7▒[01]▒6▒[01]
--> pppd: ▒7▒[01]▒6▒[01]
--> pppd: ▒7▒[01]▒6▒[01]
--> pppd: ▒7▒[01]▒6▒[01]
--> pppd: ▒7▒[01]▒6▒[01]
--> local  IP address 10.155.136.155
--> pppd: ▒7▒[01]▒6▒[01]
--> remote IP address 10.64.64.64
--> pppd: ▒7▒[01]▒6▒[01]
--> primary   DNS address 212.9.0.135
--> pppd: ▒7▒[01]▒6▒[01]
--> secondary DNS address 212.9.0.136
--> pppd: ▒7▒[01]▒6▒[01]

**Comment by c-w** [comment]
@nzola Please try setting up a client from scratch. I pushed a bunch of changes to the code and setup scripts today which should address these issues.

**Comment by nzola** [comment]
Ok. I will reinstall from scratch and give it a try, then I will report.

Thanks,
Nzola

**Comment by nzola** [comment]
this is the output of "sudo wvdial" command:
pi@raspberrypi:~ $ sudo wvdial
--> WvDial: Internet dialer version 1.61
--> Initializing modem.
--> Sending: ATZ
ATZ
OK
--> Sending: ATQ0 V1 E1 S0=0 &C1 &D2
ATQ0 V1 E1 S0=0 &C1 &D2
OK
--> Modem initialized.
--> Configuration does not specify a valid phone number.
--> Configuration does not specify a valid login name.
--> Configuration does not specify a valid password.
pi@raspberrypi:~ $

I cannot configure modem on the program. The modem window is empty.

**Comment by nzola** [comment]
The modem configuration box is empty.

[image: image.png]

**Comment by c-w** [comment]
@nzola Did you try via the sync now button?

**Comment by nzola** [comment]
Clemens,
Before you dig deeper, please tell me where the modem connect settings are
located. I want to go in there to check to make sure the provider SIM card
I am using matches the modem setting in the Lokole app.
Because last night I used the SIM from my cellphone. I want to try hologram

Thanks,
Nzola

**Comment by c-w** [comment]
The new version of the sync now button should auto-generate the wvdial configuration the first time it's being used if the SIM TYPE is set to `Hologram_World`. The wvdial configuration file should be located at `~/lokole/state/wvdial/Hologram_World`. Could you confirm this is the case?

Here's the wvdial that should be generated:

```
[Dialer Defaults]
Init1 = ATZ
Init3 = AT+CGDCONT=1,"IP","hologram"
Phone = *99***1#
Stupid Mode = 1
Username = " "
Password = " "
New PPPD = yes
Modem = /dev/ttyUSB0
```

**Comment by nzola** [comment]
I have just installed the Lokole right now and it went all well. But still
cannot connect connect to modem.
As you have explained to me, I have checked the folder to see the modem
dial up, but it looked to me that the Hologram_World was not created. See
it here:

login as: pi
pi@192.168.0.21's password:
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Jan 24 05:16:03 2019 from 192.168.0.12

SSH is enabled and the default password for the 'pi' user has not been
changed.
This is a security risk - please login as the 'pi' user and type 'passwd'
to set a new password.

pi@raspberrypi:~ $ sudo wvdial
--> WvDial: Internet dialer version 1.61
--> Initializing modem.
--> Sending: ATZ
ATZ
OK
--> Sending: ATQ0 V1 E1 S0=0 &C1 &D2
ATQ0 V1 E1 S0=0 &C1 &D2
OK
--> Modem initialized.
--> Configuration does not specify a valid phone number.
--> Configuration does not specify a valid login name.
--> Configuration does not specify a valid password.
pi@raspberrypi:~ $ ls
lokole  setup-lokole.sh
pi@raspberrypi:~ $ cd lokole
pi@raspberrypi:~/lokole $ ls
python  state
pi@raspberrypi:~/lokole $ cd state
pi@raspberrypi:~/lokole/state $ ls
emails.sqlite3    nginx_gunicorn.sock  webapp_run.sh
webapp_stdout.log
nginx_access.log  users.sqlite3        webapp_settings.env  webapp_sync.sh
nginx_error.log   webapp_restart.sh    webapp_stderr.log    wvdial
pi@raspberrypi:~/lokole/state $ cd wvdial
pi@raspberrypi:~/lokole/state/wvdial $ ls
pi@raspberrypi:~/lokole/state/wvdial $

**Comment by c-w** [comment]
What's the value of SIM_TYPE in the webapp_settings.env file? (Don't post the entire file here since it contains secrets.)

**Comment by nzola** [comment]
Ok. I will send you this file tonight

**Comment by c-w** [comment]
Send it to me via Slack, @nzola. Thanks!

**Comment by nzola** [comment]
Ok.Will do


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Clemens Wolff <notifications@github.com> Date: 2019-01-24  10:32 AM  (GMT-08:00) To: ascoderu/opwen-webapp <opwen-webapp@noreply.github.com> Cc: Nzola Swasisa <nzola8@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [ascoderu/opwen-webapp] Sync times out (#116) 
Send it to me via Slack, @nzola. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ascoderu/opwen-webapp","title":"ascoderu/opwen-webapp","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ascoderu/opwen-webapp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@c-w in #116: Send it to me via Slack, @nzola. Thanks!"}],"action":{"name":"View Issue","url":"https://github.com/ascoderu/opwen-webapp/issues/116#issuecomment-457306484"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ascoderu/opwen-webapp/issues/116#issuecomment-457306484",
"url": "https://github.com/ascoderu/opwen-webapp/issues/116#issuecomment-457306484",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by c-w** [comment]
@nzola I've just pushed release 0.1.35 which includes some more fixes for the wvdial setup path. I've confirmed that with the Huawei MS2131i-8 modem (the only one I currently have), the "Sync now" button now works as desired when the setup script is run with the SIM_TYPE script argument set to "hologram". Using this new version will require setting up a new device from scratch.

Note that the first time the button gets clicked, the "Wvdial config" box on the settings page is expected to be empty. This box will get populated with the dial-up information on the first successful sync.

Note that if there's an error for you now, we know that it's due to the usb_modeswitch codepath since the Huawei MS2131i-8 modem doesn't require mode switching. In case you don't have one yet, for easier debugging I'd encourage you to buy one. At the time of writing, they can be found for [$17.95 on AliExpress](https://www.aliexpress.com/item/unlocked-Huawei-MS2131i-8-USB-modem-industrial-use-Linux-supported/32964337576.html) which is a great deal. I will also order a modem that requires modeswitching so that I can fully debug that code path.

**Comment by nzola** [comment]
I have tried new installation twice and I got this error and the install
stops right here:

Get:3 http://raspbian.mirror.colo-serv.net/raspbian stretch/main armhf jq
armhf 1.5+dfsg-1.3 [58.9 kB]
Fetched 305 kB in 1s (222 kB/s)
Selecting previously unselected package libonig4:armhf.
(Reading database ... 34399 files and directories currently installed.)
Preparing to unpack .../libonig4_6.1.3-2_armhf.deb ...
Unpacking libonig4:armhf (6.1.3-2) ...
Selecting previously unselected package libjq1:armhf.
Preparing to unpack .../libjq1_1.5+dfsg-1.3_armhf.deb ...
Unpacking libjq1:armhf (1.5+dfsg-1.3) ...
Selecting previously unselected package jq.
Preparing to unpack .../jq_1.5+dfsg-1.3_armhf.deb ...
Unpacking jq (1.5+dfsg-1.3) ...
Setting up libonig4:armhf (6.1.3-2) ...
Setting up libjq1:armhf (1.5+dfsg-1.3) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up jq (1.5+dfsg-1.3) ...
*Unsupported sim-type: Hologram_World*

**Comment by c-w** [comment]
When you call the script, now use "hologram", not "Hologram_World".

**Comment by nzola** [comment]
I see...

**Comment by nzola** [comment]
The install, modem and mail transfers are all working without any problems
now.

**Comment by nzola** [comment]
Yes. I checked it before Sync Now it was empty and populated after the
first sync.

**Comment by c-w** [comment]
Very good. Resolving this.

**Comment by nzola** [comment]
I have tried using a different SIM from version Mobile and changing the IP (APN) number in the "Sync Now" to much version mobile network , it seems not to connect to the modem. In the past it worked with Version mobile and Telus. I will reconfirm this before making it an issue.
