### ISSUE TITLE
Local Lokole administration tasks

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#14]
Local Lokole admin login option to access Lokole administration page to manage the users.

**Comment by c-w** [comment]
We already have an [admin page](https://github.com/ascoderu/opwen-webapp/blob/de43d220f06eaf3cf60217e5dc79787d7ba0b279/opwen_email_client/webapp/templates/admin.html) that:
- Displays all the users on the Lokole and when they were last active.
- Enables blocking and unblocking of accounts. A blocked account can't log into the Lokole system anymore.

Are there any additional administration tasks that we need to cover?

**Comment by nzola** [comment]
Perfect!
No additional thought for now. Just to confirm that users passwords retrieve is also on the admin task.

**Comment by c-w** [comment]
Yes, password restore will be on the admin page once it's implemented. Resolving this in favor of #12.

**Comment by nzola** [comment]
Good, Thanks!
