### ISSUE TITLE
Date and time

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#15]
All the Lokole emails listing in the INBOX and SENT have the same date and time on the right columns. This date and time are current.

**Comment by c-w** [comment]
Hm, interesting. Thanks for reporting. This is something we need to look into. Two places to start the investigation: (1) double-check that the email `sent_at` time on the server is reasonable (2) double-check the frontend logic that converts the UTC email sent time to local time.

**Comment by c-w** [comment]
Here are two extract from some of the received emails (i.e., inbox on the Lokole) as seen by the email service:

```json
"sent_at":"2017-03-03 10:54"
"sent_at":"2017-03-05 20:46"
```

The emails were received on 3/3/2017, 2:54:09 AM and 3/5/2017, 12:46:26 PM respectively, so the data on the server looks reasonable to me, so the date formatting bug must be on the email client application. A place to start looking is the [_emails_view](https://github.com/ascoderu/opwen-webapp/blob/de43d220f06eaf3cf60217e5dc79787d7ba0b279/opwen_email_client/webapp/views.py#L285-L288) method which converts the email dates from UTC to local time before displaying them to the user.

**Comment by c-w** [comment]
![image](https://user-images.githubusercontent.com/1086421/30248905-5b13f370-9630-11e7-9632-5338cf029b46.png)
