### ISSUE TITLE
Web address re-direction

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#16]
To redirect any web address type on address bar to ascoderu.ca.
When one connect to the Lokole network, open the browser, has to type ascoderu.ca to access ascoderu email system. Can you implement any web address redirect clients to ascoderu.
This will have to benefits
1 - the user don't have to remember ascoderu.ca
2 - Ascoderu publicity to a pass by; I carry Lokole powered up with battery in my bag in the bus everyday. I know many smart phone users on the bus they see ascoderu network. If these people can access at least the front page, they would be interested to read and maybe donate. This may happen in DRC, too.

**Comment by c-w** [comment]
I looked into this when I was implementing the prototype and it's more complicated than I initially thought.

My first attempt was to add some code to the Lokole [configuration script](https://github.com/ascoderu/opwen-setup/blob/master/setup-webapp.sh) that resolves all DNS addresses on the Lokole to ascoderu.ca, but then that messes with the HTTP calls we have to make at email-sync time. I'll have to look more deeply into Linux arcana to set this up.

How much of a priority is this? I estimate this will take at least a week of full-time effort to investigate and set up.

**Comment by nzola** [comment]
This is not a priority. It can be done later

Thanks,
Nzola

**Comment by c-w** [comment]
Resolving in favour of [opwen-setup#7](https://github.com/ascoderu/opwen-setup/issues/7).
