### ISSUE TITLE
Sync sometimes gets delayed

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#163]
From @nzola

> Sometimes the Lokole receive/send emails at every connections, but more then 70% of the time it takes a day before mail transactions happen. The Lokole sync operation works normally (auto and manual).

**Comment by c-w** [comment]
@nzola A couple of follow-up questions to help me investigate:

1. Does eventually the mail still get delivered or does the system fail entirely to deliver the mail?
2. Is the behavior consistent with SIM and Ethernet mode or does it only happen in one of the two?
3. Does the delay also happen when you only send small emails or does it only happen with large emails?

**Comment by nzola** [comment]
I want to answer to these investigation questions correctly, so I have to
setup one Ethernet Lokole and 3 SIM Lokoles to observe the behaviours.
I will have the answer by the end of this week.

**Comment by c-w** [comment]
Closing as a duplicate of https://github.com/ascoderu/opwen-webapp/issues/169
