### ISSUE TITLE
New incoming mail position

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#17]
As per now, all the new emails come at the bottom of the last page.
Can this be modified to position new incoming emails on top of the first page

**Comment by c-w** [comment]
This should be relatively easy. I reckon we can achieve this for all email views (inbox, sent, outbox, search) by adding an `.order_by(_Email.sent_at.desc())` clause to the method that retrieves the data from the email database: [_SqlalchemyEmailStore._query](https://github.com/ascoderu/opwen-webapp/blob/de43d220f06eaf3cf60217e5dc79787d7ba0b279/opwen_email_client/domain/email/store.py#L173-L177). The only limitation is that the `sent_at` column is currently a string -- to have a meaningful sort, we should instead store the date as a `DATETIME` or as an `INTEGER`.
