### ISSUE TITLE
Add indicator for number of emails to be synced

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#170]
From @nzola 

> Is there a way for us to see stuck queued emails in the main server and be able to push (Sync) them to the users?

**Comment by nzola** [comment]
Will this implementation show the number of emails do be sync'ed from the
cloud to the Lokole or vice versa?

**Comment by c-w** [comment]
@nzola From the Lokole to the cloud. Do you also wish to see the opposite direction (from the cloud to all Lokoles)?

**Comment by nzola** [comment]
Yes. But for us in Azure. Not for the Lokole Admins. It will not be good
for them to manipulate the cloud.

**Comment by c-w** [comment]
@nzola I've created a new issue on the server repo for this: https://github.com/ascoderu/opwen-cloudserver/issues/185

**Comment by nzola** [comment]
Thank you!

**Comment by nzola** [comment]
Do I need a new script to setup new Lokoles or use the actual?

**Comment by c-w** [comment]
@nzola You can use the normal script (it's also been updated). Just make sure to download the latest version from master via the usual `curl -O https://raw.githubusercontent.com/ascoderu/opwen-webapp/master/install.py`.

**Comment by nzola** [comment]
Thank you and good night Clemens!
