### ISSUE TITLE
Carrier return to inbox

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#18]
When one composes new email and click send. It says ; email is sent, but the mail sent still show on the front page as if it is not sent.
Can the front page returns to INBOX after one click the send?

**Comment by c-w** [comment]
This is easy. In the [email_new](https://github.com/ascoderu/opwen-webapp/blob/de43d220f06eaf3cf60217e5dc79787d7ba0b279/opwen_email_client/webapp/views.py#L103-L115) view, we just need to return a redirect to the inbox using `redirect(url_for('email_inbox'))`.

**Comment by nzola** [comment]
Thanks!
