### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#24]
Sudheesh is a researcher who has a lot of experience in frontend for developing countries. This issue is to track any improvement ideas he has for the Lokole app.

@nzola and @laura-barluzzi may be interested in this too.

**Comment by sudheesh001** [comment]
- [ ] Updated Nav banner
<img width="1439" alt="new_top_banner" src="https://user-images.githubusercontent.com/4545925/29310736-9c3b7328-81cc-11e7-92b0-444b960402e7.png">

- [ ] New Inbox View
![inbox](https://user-images.githubusercontent.com/4545925/29310764-b8053f80-81cc-11e7-8f99-67f141782ec1.png)

- [ ] Create New email
![createemail](https://user-images.githubusercontent.com/4545925/29310769-bf573a9a-81cc-11e7-8e92-86043c99cfb3.png)

- [ ] Mobile UI/UX
![mobile_layout](https://user-images.githubusercontent.com/4545925/29310777-c473ff0e-81cc-11e7-9169-092b567a0cf9.png)

**Comment by c-w** [comment]
See https://github.com/ascoderu/opwen-webapp/pull/42

**Comment by c-w** [comment]
Resolving since the underlying PR was closed for inactivity.
