### ISSUE TITLE
Create a tropicalized case

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#32]
**What's this?**

We'll be deploying the Lokole device hardwares in tropical climates. As such, we should enclose the hardware and peripherals (USB modem, battery) in a case that protects the device against dust, high temperatures, moisture, etc.

The quality and performance of the case will directly influence the longevity of the Lokole devices. As such, the better job we do here, the less our users will have to spend on replacing parts of the hardware, saving money for the rural African communities.

**Getting started**

We have two hardware models that we support so we'll have to design two cases (focus on the OrangePi first as it's the cheaper hardware so we'll deploy more of these):

[OrangePi Zero](https://goo.gl/LHzZAF)
<img src="https://user-images.githubusercontent.com/1086421/28235540-b0450670-68c4-11e7-8a7f-85daf6ea899b.png" width=200 />

[Raspberry Pi 3](https://goo.gl/dvjWJk)
<img src="https://user-images.githubusercontent.com/1086421/28235542-c75097d0-68c4-11e7-9216-835ffeebde57.png" width=200 />

Additionally, the case will have to enclose an optional battery and a required USB modem like [Huawei E3131](https://goo.gl/giqfJg).

<img src="https://user-images.githubusercontent.com/1086421/28235549-f3803e78-68c4-11e7-9618-9ae30f51c525.png" width=200 />

Imported from https://github.com/ascoderu/opwen-setup/issues/6

**Comment by c-w** [comment]
From Shaun:

> @nzola mentioned the addition of a battery pack. Is there a specific model or type that you have started to work with so I can best include it in my considerations.

We don't yet have a canonical/recommended battery pack for the project. It would be amazing if you could do some research on the best battery pack we should be using (price/performance ratio) and make a recommendation.

> Reading through the reports on github, I saw mention to moving email storage out of the SD card to another HD format, has there been progress with this? As I can pencil in this expansion capability to the design.

There hasn't been progress on this. The main intention here is to reduce the IO to the SD card since this can lead to corruption after prolonged periods of use. Ideally we'd have a small USB stick or USB drive attached to the device and only use the SD card for the OS. I haven't done much research in this area yet so again if you could do some digging and make some recommendations that would be amazing. Thanks in advance!

**Comment by c-w** [comment]
I believe @nzola managed to get a tropicalized case put together. @nzola: do we have assets to reproduce the Lokole case somewhere so that we can store them for the future (e.g. a CAD file or some-such)?

**Comment by sbathgate** [comment]
I have uploaded all the design files for the tropicalized case on the following: https://github.com/sbathgate/lokole-case-design

**Comment by c-w** [comment]
Great, thanks @sbathgate! Would you mind [transferring the repo](https://help.github.com/en/articles/transferring-a-repository) to the Ascoderu organization so that we can have everything under one umbrella? I just sent you an invite to the organization which should give you all the permissions required to create new repos, have push access, etc. Thanks in advance!
