### ISSUE TITLE
Move away from Bower

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#35]
As per `npm install`, Bower is deprecated and we should move to Yarn.

> npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by laura-barluzzi** [comment]
@c-w I finished this task but I cannot push code to this app.
![image](https://user-images.githubusercontent.com/16849118/43176812-6660dc54-8f93-11e8-9fff-4a1da5dea278.png)

Please could you grant me access to the webapp as well? Cheers

**Comment by c-w** [comment]
Done, @laura-barluzzi
