### ISSUE TITLE
Integrate with Internet-in-a-Box

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#37]
The Internet-in-a-Box project ([Website](http://internet-in-a-box.org/), [Github](https://github.com/iiab/iiab)) is interested in onboarding Lokole as a local-only email service.

To make this integration happen, we'll need to build out a few things:

- [x] Create an Ansible playbook to deploy Lokole (currently we deploy via bash scripts).
- [x] Wrap Lokole in a systemd service for management (currently we use supervisord).
- [x] Enable Lokole to use a MySQL database (currently we use SQLite).

**Comment by tim-moody** [comment]
Looks good. BTW, IIAB has sqlite installed as some services use it, if that is a preference.

**Comment by c-w** [comment]
@rgangela99, @aidan-fitz, @viviancaiyw

**Comment by aidan-fitz** [comment]
@rgangela99 and I are working on this issue in [my fork here](https://github.com/aidan-fitz/opwen-webapp/tree/iiab-integration).

**Comment by aidan-fitz** [comment]
To create the Ansible playbook, we'll follow these steps:

[ ] Translate the `setup/setup-lokole.sh` script into a flowchart showing the main steps.
[ ] Look for Ansible modules that match the steps in the setup script.
[ ] Translate the flowchart into a playbook using those modules.

**Comment by holta** [comment]
Lokole is now integrated into Internet-in-a-Box:  See https://github.com/iiab/iiab/pull/1284

Please all consider these 2 short lists of suggestions for Lokole going forward: https://github.com/iiab/iiab/pull/1282#issuecomment-435622419

Thanks all for making this happen over these 6+ months of gestation since March 2018!

**Comment by c-w** [comment]
Resolving this since Lokole support for IIAB has been merged. Let's track any bugs or leftover work in new issues. Thanks all for making this happen!
