### ISSUE TITLE
Add retry to email sync script

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#39]
@nzola said:

> Cell Lokole connects most of the time, but sometimes skips the connection and connects in the next round.

This is likely because of intermittent connectivity issues dialing up with the USB modem. We can add a retry wrapping the sync script to avoid this.

The sync script is generated by [setup-lokole.sh](https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/setup/setup-lokole.sh#L562-L636) when a new device is being provisioned. ~~There's also a simpler version of this script that gets generated in [setup-lokole-docker.sh](https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/setup/setup-lokole-docker.sh#L139). So both places would have to be updated to retry the sync a few times.~~

**Comment by laura-barluzzi** [comment]
@c-w  does something on these lines work? 
```
   n=0
   until [ $n -ge 5 ]
   do
      write_file "${opwen_webapp_email_sync_script}" << EOF && break
      n=$[$n+1]
      sleep 15
   done
```
I know there are different ways to implement this logic but I mainly wonder if we aim to:
1. Retry the command a few times
2. Retry the command only once based on a return value/status code

**Comment by c-w** [comment]
We aim to retry the sync itself, not the generation of the sync script. The sync is done by the `main` function in the sync script: https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/setup/setup-lokole.sh#L627-L633

The sync should be retried only if it failed (so it the command had a non-zero exit code).

The retry logic you sketched out above looks good, but ideally we'd use an [exponential backoff](https://dzone.com/articles/understanding-retry-pattern-with-exponential-back) retry strategy (so at each attempt, sleep twice the time than during the last attempt).

**Comment by c-w** [comment]
To implement the retry cleanly, you could introduce a `main_with_retry` function that wraps the `main` function and adds the retry logic to it.
