### ISSUE TITLE
Implement "heartbeat" email that gets sent on each sync

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#71]
I don't know if this is asking to much from the system. Can the Lokole device has an automatic SEND EMAIL script. At every time the Lokole device connect to the local cell network, it will send an email to me saying for instance; OPERATION OK!  This email address will be separate from my normal email addresses.
This will help me question the person in charge what is happen to the Lokole if I don't see any emails.
I have had this experience in the past without knowing what is going with the device and I had to tell the operator to send me one email everyday, but it did not work as they did not send any on some days. I thought this is good, especially for the pilot project.

**Comment by c-w** [comment]
This should be pretty straight forward. We configure a "heartbeat email address" and then whenever the sync happens we generate an automatic email that gets sent to this email address.

This can all be implemented in [SyncEmails.upload](https://github.com/ascoderu/opwen-webapp/blob/3046cd28c21cbe2cae3a532eaf7b92e3f1ff1150/opwen_email_client/webapp/actions.py#L17-L26) by generating the heartbeat email and adding it to the `pending` list. The rest will happen automatically.

@laura-barluzzi: you just did some changes in the same area of the code, would you be interested in taking on this task?

**Comment by laura-barluzzi** [comment]
@nzola We discussed about the purpose of this and we thought that the best way to go would be to analyse existing data creating graphs with the log message we have in Azure Portal > Application Insight > Analytics.

I created 4 starting graphs showing total of emails exchanged in the past week, on a daily basis. There are 4 exchange types with a graph each:
- [Lokole cloud-server << Lokole client domains](https://portal.azure.com#@6688d401-28a2-4780-a5a7-7cc6ff1b40ba/blade/Microsoft_OperationsManagementSuite_Workspace/AnalyticsBlade/initiator/AnalyticsShareLinkToQuery/isQueryEditorVisible/true/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F7251246a-f6e5-4759-a1a1-4dc4a730ee4d%2Fresourcegroups%2Fopwendata%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fopwenlogsopzrs57fzm73k%22%7D%5D%7D/query/H4sIAAAAAAAAA22QsW7DMAxE93wFkSU2EHft5E7tGGTuJLASnaixxICik7rox1dWk9oFqknAvSOPZ4ekHF4uFDWtvuB6JCGIGAjaFtYU0PfJCFnyF3KmEw7G9j7T619afaCkGM7wBHjg6tHVWaMPpejA4bjvXgkF2hn8I6esdCwB1ThUmqBKef7eTfUWNmN%2BzW7XuM1yBeeUcRqjnFR8PFS2XPWcrTF5junhh5lMaQgBxX8SWB6iVjW8jSXG9j5oO4fOPIsjuTG3SzBZgCydhd%2FJaoNXXMoLRahUqazYm1Lmv13m6CWMmbzZUzai2COKwslH1w4xd2BP5FbfRntvl7EBAAA%3D/isQueryBase64Compressed/true/timespanInIsoFormat/P1D) (Lokole cloud-server received emails from Lokole clients)
- [Lokole cloud-server >> Lokole client domains](https://portal.azure.com#@6688d401-28a2-4780-a5a7-7cc6ff1b40ba/blade/Microsoft_OperationsManagementSuite_Workspace/AnalyticsBlade/initiator/AnalyticsShareLinkToQuery/isQueryEditorVisible/true/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F7251246a-f6e5-4759-a1a1-4dc4a730ee4d%2Fresourcegroups%2Fopwendata%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fopwenlogsopzrs57fzm73k%22%7D%5D%7D/query/H4sIAAAAAAAAA3WQsW7DMAxE93wFkSU2YHft5E7tGGTuJLASk6ixxECik7rox5dWk9odqknAuyOPZ4csHF4uFCWvvuB6pEQQMRB0HawpoO%2BzcdT7iwJnhI3tvYrXv2LxgbJgOMMT4IGrR1crow%2Bh6MDhuNu%2FEiboZuEfnJXsOQUU41BoElXC8%2FduqhvYjPra7bZ1m%2BUK1pBxGiOcJfl4qGw56lmtMXuO%2BeFHM5nyEAIm%2F0lgeYhS1fA2lhjNfVAzh1Y9J0fpprldgtkCKDonficrLV5xiRckUWlSWLA3%2F3ep0UsYM3nVUzZiskdMAicfXTdE7cCeyK2%2BAfE54EqwAQAA/isQueryBase64Compressed/true/timespanInIsoFormat/P1D) (Lokole cloud-server delivered emails to Lokole clients)
- [Lokole cloud-server << External client](https://portal.azure.com#@6688d401-28a2-4780-a5a7-7cc6ff1b40ba/blade/Microsoft_OperationsManagementSuite_Workspace/AnalyticsBlade/initiator/AnalyticsShareLinkToQuery/isQueryEditorVisible/true/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F7251246a-f6e5-4759-a1a1-4dc4a730ee4d%2Fresourcegroups%2Fopwendata%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fopwenlogsopzrs57fzm73k%22%7D%5D%7D/query/H4sIAAAAAAAAA3WQsW7DMAxE93wFkSU2YHft5E7tGGTuJLASk6ixpICik7rox5dWk9odqknAvSOPZ4csKbxcKEpefcH1SEwQMRB0HawpoO8NkyV%2FIWf2iY3tvbLrX1Z8oCwYzvAEeEjVo6tVow%2Bh6MDhuNu%2FEjJ0M%2FhHzqro2IBiHApNUCVp%2Ft5NdQObUV%2B73bZus1yRNGOcxkjKwj4eKltuelZrzD7F%2FPDDTKY8hIDsPwlsGqJUNbyNJUZzH9TMoZVP7IhvzO0SzBZApTOnd7LS4hWX8kJhKkVKEuzNv1Vq8pLFTFa1lIXI9ogscPLRdUPUCuyJ3Oob6m%2FciK4BAAA%3D/isQueryBase64Compressed/true/timespanInIsoFormat/P1D), e.g. gmail (Lokole cloud-server received emails from External client)
- [Lokole cloud-server >> External client](https://portal.azure.com#@6688d401-28a2-4780-a5a7-7cc6ff1b40ba/blade/Microsoft_OperationsManagementSuite_Workspace/AnalyticsBlade/initiator/AnalyticsShareLinkToQuery/isQueryEditorVisible/true/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F7251246a-f6e5-4759-a1a1-4dc4a730ee4d%2Fresourcegroups%2Fopwendata%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fopwenlogsopzrs57fzm73k%22%7D%5D%7D/query/H4sIAAAAAAAAA32QMU%2FDQAyF9%2F4Kq0sTqWFlChOMVWemyNw57dHcufI5LUH8eJzQkrBwk3Xve%2FazXZ%2BV48uFkubVF1yPJAQJI0Fdw5oihq7x1IWL%2FfumFY6N64LR619aQ6SsGM%2FwBHjg4tGXptGHUvLgcdi3r4QC9Qz%2BkbMpLUtEbTwqjVChPJd3U7mFzWCv2u0qv1mOYEuZxjbKWSWkQ%2BGmrZ7NmnLglB9%2BmNGU%2BxhRwieB4z5pUcLbMMXY3htt59DGs3iSG3PbBLMDMOks%2FE5OK7ziUl4oQtMplRW75p9jWvYpTTOazTSNRHFHFIVTSL7ukx3BncivvgEF5%2FaQsgEAAA%3D%3D/isQueryBase64Compressed/true/timespanInIsoFormat/P1D), e.g. gmail (Lokole cloud-server delivered emails to External client)

Please try to log in to the Azure Portal, copy-and-paste these graphs and let me know if this serves the purpose of the task (e.g. getting metrics of how many emails are sent etc). We could consider to expands the logs and graphs once we have more ideas.

**Comment by nzola** [comment]
Hi Laura,
Metric are very important for an organization self assessment for future planning and for external visibility to show and tell accurately, for our case the frequency of email traffic.
Where do you want me to paste the graphs from the portal, here in giThub #71

**Comment by c-w** [comment]
@nzola The graphs are for you to use and review as you see fit. For example, you can use the graphs to see which clients are sending emails and how many they're sending (which I believe was the original ask behind this task). Are you happy with these graphs for providing the monitoring functionality you requested (if so, we'll close this issue) or would you like some additional features?

**Comment by c-w** [comment]
I've published a dashboard based on the queries that Laura wrote. See screenshot below:

![Screenshot showing analytics dashboard](https://user-images.githubusercontent.com/1086421/56872675-c2f32a80-69f9-11e9-95f0-e2943785134c.png)

This dashboard should contain a lot of the relevant "business telemetry" information. If you require additional insights, please let me know @nzola, and we can discuss how to best add the visualizations.

@nzola @laura-barluzzi You should be able to access the dashboard via this [link](https://portal.azure.com/#@ascoderuopwengmail.onmicrosoft.com/dashboard/arm/subscriptions/7251246a-f6e5-4759-a1a1-4dc4a730ee4d/resourceGroups/dashboards/providers/Microsoft.Portal/dashboards/9acf2952-ca98-426a-b17d-48e31e534483) with your GMail accounts. Let me know if this is not the case.
