### ISSUE TITLE
The Lokole Admin and User Manual

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#77]
I propose we start writing the Admin and user Manual which will include the installation, setup and operation of the Lokole device. It looks like there is a lot of information already in the developer description written by Clemens Wolff.

**Comment by c-w** [comment]
@nzola Please write a Word document with the content you'd like and share it with me privately. Then I can add it to the Lokole app as an admin-only page. Thanks!

**Comment by nzola** [comment]
@Clemens Message received

**Comment by holta** [comment]
A small (but great!) piece of Lokole documentation is evolving here:
https://github.com/iiab/iiab/tree/master/roles/lokole#lokole-readme

As linked to from Internet-in-a-Box's FAQ:
http://wiki.laptop.org/go/IIAB/FAQ#What_can_I_do_with_E-books_and_Internet-in-a-Box.3F

_(Please feel free to edit both above documents !)_

Ref: #81

**Comment by c-w** [comment]
[The Lokole-IIAB User's Manual.pdf](https://github.com/ascoderu/opwen-webapp/files/2745730/The.Lokole-IIAB.User.s.Manual.pdf)
