### ISSUE TITLE
Emails stuck in outbox

### ISSUE THREAD

**Issue by aidan-fitz** [ascoderu/opwen-webapp#80]
@holta says:

> Some emails (including the 1st email sent?) are permanently stuck in the "Outbox" folder (rather than the "Sent" folder) even despite the fact the email was successfully sent _(seems less important)_

at iiab/iiab#1282

**Comment by c-w** [comment]
To what account did you send the emails? The only emails that go straight into "Sent" are emails to accounts on the same device, i.e. with the same email domain name as the sender. Everything else goes into "Outbox" and given that IIAB will never connect to internet, those emails will never leave the Outbox.

**Comment by holta** [comment]
> To what account did you send the emails? The only emails that go straight into "Sent" are emails to accounts on the same device, i.e. with the same email domain name as the sender. Everything else goes into "Outbox" and given that IIAB will never connect to internet, those emails will never leave the Outbox.

Ok.  Confusing but yes this corroborates the theory that the glitch occurred b/c I cc'd an actual/online email account.

**Comment by c-w** [comment]
Resolving given that the functionality here is as expected. We'll document the "offline only" aspect in #81.
