### ISSUE TITLE
Update IIAB documentation

### ISSUE THREAD

**Issue by holta** [ascoderu/opwen-webapp#81]
Which of these 3+4 Lokole questions/suggestions might possibly be achievable in 2019?

https://github.com/iiab/iiab/pull/1282#issuecomment-435622419

**Comment by c-w** [comment]
Thanks for the questions. 3 of the 4 suggestions are all implemented and ready to be documented by @aidan-fitz: user suspension, password reset and customized email domain name. The remaining suggestion (local-only emails) is also a documentation task.

I'll take a look at the bug reports next.

**Comment by c-w** [comment]
Will handle the bug reports in their own issues:
- https://github.com/ascoderu/opwen-webapp/issues/79
- https://github.com/ascoderu/opwen-webapp/issues/80

Assigning this to @aidan-fitz since it's now a documentation task.

**Comment by c-w** [comment]
Changing issue title to reflect the documentation updates that are required as per https://github.com/iiab/iiab/pull/1282#issuecomment-435704091.

**Comment by holta** [comment]
This critical documentation should probably be placed here:
https://github.com/iiab/iiab/blob/master/roles/lokole/README.rst

I and others can then contextualize that for wider audiences in places like:
http://FAQ.IIAB.IO
https://github.com/iiab/iiab/wiki
